config/routes.rb
Rails.application.routes.draw do
  resources :rooms  
  resources :beds
  resources :diagnoses
  resources :departments
  resources :department_doctors
  resources :patients do  
  end  
  get 'visit/:id/prescription_detail' => 'visits#prescription_detail', :as=>"prescription_details"
  get '/opd_visit' => 'visits#opd_visit', :as=>"opd_visits"
 
  get '/dashboard'  => 'visits#dashboard', :as=>"dashboard"
  get '/billing'  => 'visits#billing', :as=>"billing"
  get '/paid_bill'  => 'visits#paid_bill', :as=>"paid_bill"
  get '/visit/:visit_id/report_genrate' => 'reports#genrate_report', :as=>"genrate_report" 
  get '/visit/:visit_id/print_receipt' => 'diagnoses#print_receipt', :as=>"print_receipt"  
  
  post '/download_paid_bill'  => 'reports#download_paid_bill', :as=>"downlaod_paid_bill"

  resources :services do 
    
  end   
 

  resources :patient do  
     resources :appointments,only: [:new, :create,:edit,:update] do
    end
  end 

  resources :appointments

  resources :patients do 
     resources :visits do
    end
  end 

  resources :visits do 
    resources :prescription_details,only: [:index, :new, :create,:destroy] do
    end  
  end  

  resources :visits do
    resources :diagnoses do
    end  
  end 

  resources :visits do
    resources :notes do
    end 
  end 

  resources :visits do
    resources :worksheet_details do
    end  
  end 

  resources :discharges
  resources :visits do
    resources :discharges, only: [:new, :create] do
    end  
  end 

  resources :visits do
    resources :visit_rooms, only: [:new, :create,:index,:destroy] do
    end  
  end 

  resources :visits do 
    resources :operation_theaters,  only: [:new,:create,:index,:show] do
    end
  end    

  get '/ipd_visits' => 'visits#ipd_visits', :as=>"ipd_visits"
  get '/visit/:id/basic_detail' => 'visits#basic_detail', :as=>"basic_detail"

 
  devise_for :users
  resources :user
  
  resources :visits do
    get 'all_services' 
    get 'report'
    get 'genrate_bill'
  end  

  get 'visit/:visit_id/payment/new' => 'payments#new', :as=>"payment_new"
  post 'visit/:visit_id/payments' => 'payments#create', :as=>"create_payment"
  post 'visit/:visit_id/payment' => 'payments#payment', :as=>"payment"
  get '/report' => 'reports#index', :as=>"report"

    
  post  '/search_category_room' => 'visits#search_category_room',:as=>"search_category_room"
  post '/search_visit'  => 'visits#search_visits', :as=>"search_visits"

  get '/bed/:bed_id/admit' => 'beds#admit',:as=>"admit"
  get '/country/:country_id/states' => 'patients#states',:as=>"states"
  get '/state/:state_id/cities' => 'patients#cities',:as=>"cities" 

  root 'user#index'

  resources :visits do
    resources :visit_services do 
    end
  end  

  resources :medicines do 
  end  
  get '/export' => 'medicines#export',:as=>"export"
  

resources :categories

end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :addmission
	belongs_to :visit

	validates :date, :time,:progress,:treatment, :presence=>true
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_visit, only:[:new ,:create,:destroy,:index] 
  layout 'patient'
  # GET /notes
  # GET /notes.json
  def index
    @notes = @visit.notes
  end

  def show
  end

  def new
    @note = Note.new
  end


  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = @visit.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to visit_notes_path(@visit), notice: 'Note was successfully created.' }
        
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find_by_visit_id(params[:visit_id])
    @note.destroy
    respond_to do |format|
      format.html { redirect_to  visit_notes_path(@visit), notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    def set_visit
       @visit = Visit.find(params[:visit_id])
    end  


    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:date, :time, :progress, :treatment, :user_id, :remarks)
    end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
  <div class="col-sm-8">
    <div class="panel panel-default">
      <div class="panel-heading"> Progress notes </div>
        <div class="panel-body">

          <%= form_for [@visit, @note] do |f| %>
            <% if @note.errors.any? %>

              <ul>
              <% @note.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            <% end %>

            <div class="field">
              <%= f.label :date %><br>
              <%= f.text_field :date,:class=>"form-control",:id=>"start_date_picker" %>
            </div>
            <div class="field">
              <%= f.label :time %><br>
              <%= f.text_field :time,:class=>"form-control", id: 'timepicker' %>
            </div>
            <div class="field">
              <%= f.label :progress %><br>
              <%= f.text_field :progress,:class=>"form-control" %>
            </div>
            <div class="field">
              <%= f.label :treatment %><br>
              <%= f.text_field :treatment,:class=>"form-control" %>
            </div>
              <%#= f.label :user_id %>
              <%#= f.number_field :user_id,:class=>"form-control" %>
            <div class="field">
              <%= f.label :remarks %><br>
              <%= f.text_field :remarks,:class=>"form-control" %>
            </div>
            <div class="actions">
              <%= f.submit 'save',:class=>"btn btn-primary", :style=>"margin-top: 15px;" %>
            </div>
          <% end %>
        </div>  
    </div>
  </div>



<script>
    $('#start_date_picker').datepicker({
        format: 'yyyy-mm-dd',
        daysOfWeekDisabled: [0, 6],
        daysOfWeekHighlighted: [1, 2, 3, 4, 5],
        todayBtn: false
    })
</script>


<script>
  $(function() {
    $('#timepicker').timepicker();
  });
</script>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<table class="table table-striped">
  <thead >
    <tr>
      <th>Date</th>
      <th>Progress</th>
      <th>Treatment</th>
      <th>Remarks</th>
      <th>User</th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.date %></td>
        <td><%= note.progress %></td>
        <td><%= note.treatment %></td>
        <td><%= note.remarks %></td>
        <td><%= note.user_id %></td>
        <td><%=link_to'Remove', visit_note_path(note.visit,note ),method: :delete %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<%=link_to'Add notes', new_visit_note_path(@visit),:class=>"btn  btn-primary"%>

<br>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @note.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @note.time %>
</p>

<p>
  <strong>Progress:</strong>
  <%= @note.progress %>
</p>

<p>
  <strong>Treatment:</strong>
  <%= @note.treatment %>
</p>

<p>
  <strong>User:</strong>
  <%= @note.user_id %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @note.remarks %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>