config/routes.rb
Rails.application.routes.draw do
  resources :rooms  
  resources :beds
  resources :diagnoses
  resources :departments
  resources :department_doctors
  resources :patients do  
  end  
  get 'visit/:id/prescription_detail' => 'visits#prescription_detail', :as=>"prescription_details"
  get '/opd_visit' => 'visits#opd_visit', :as=>"opd_visits"
 
  get '/dashboard'  => 'visits#dashboard', :as=>"dashboard"
  get '/billing'  => 'visits#billing', :as=>"billing"
  get '/paid_bill'  => 'visits#paid_bill', :as=>"paid_bill"
  get '/visit/:visit_id/report_genrate' => 'reports#genrate_report', :as=>"genrate_report" 
  get '/visit/:visit_id/print_receipt' => 'diagnoses#print_receipt', :as=>"print_receipt"  
  
  post '/download_paid_bill'  => 'reports#download_paid_bill', :as=>"downlaod_paid_bill"

  resources :services do 
    
  end   
 

  resources :patient do  
     resources :appointments,only: [:new, :create,:edit,:update] do
    end
  end 

  resources :appointments

  resources :patients do 
     resources :visits do
    end
  end 

  resources :visits do 
    resources :prescription_details,only: [:index, :new, :create,:destroy] do
    end  
  end  

  resources :visits do
    resources :diagnoses do
    end  
  end 

  resources :visits do
    resources :notes do
    end 
  end 

  resources :visits do
    resources :worksheet_details do
    end  
  end 

  resources :discharges
  resources :visits do
    resources :discharges, only: [:new, :create] do
    end  
  end 

  resources :visits do
    resources :visit_rooms, only: [:new, :create,:index,:destroy] do
    end  
  end 

  resources :visits do 
    resources :operation_theaters,  only: [:new,:create,:index,:show] do
    end
  end    

  get '/ipd_visits' => 'visits#ipd_visits', :as=>"ipd_visits"
  get '/visit/:id/basic_detail' => 'visits#basic_detail', :as=>"basic_detail"

 
  devise_for :users
  resources :user
  
  resources :visits do
    get 'all_services' 
    get 'report'
    get 'genrate_bill'
  end  

  get 'visit/:visit_id/payment/new' => 'payments#new', :as=>"payment_new"
  post 'visit/:visit_id/payments' => 'payments#create', :as=>"create_payment"
  post 'visit/:visit_id/payment' => 'payments#payment', :as=>"payment"
  get '/report' => 'reports#index', :as=>"report"

    
  post  '/search_category_room' => 'visits#search_category_room',:as=>"search_category_room"
  post '/search_visit'  => 'visits#search_visits', :as=>"search_visits"

  get '/bed/:bed_id/admit' => 'beds#admit',:as=>"admit"
  get '/country/:country_id/states' => 'patients#states',:as=>"states"
  get '/state/:state_id/cities' => 'patients#cities',:as=>"cities" 

  root 'user#index'

  resources :visits do
    resources :visit_services do 
    end
  end  

  resources :medicines do 
  end  
  get '/export' => 'medicines#export',:as=>"export"
  

resources :categories

end

app/models/visit.rb
class Visit < ActiveRecord::Base
	belongs_to :patient
	belongs_to :user ,:foreign_key => :doctor_id
	has_one :basic_detail
	has_many :prescription_details
	#has_one :addmission
	has_many :diagnoses
	has_many :worksheet_details 
	has_many :notes
	has_one :discharge
	has_many :services
	has_one :payment
	
	has_many :visit_rooms
	has_many :rooms, :through=>:visit_rooms
	has_many :operation_theaters
	after_create :booked_bed
	after_create :update_start_date

	accepts_nested_attributes_for :services
	accepts_nested_attributes_for :visit_rooms

	has_many :visit_services 
	has_many :services ,:through=>:visit_services

	validates :doctor_id, :date, :presence=>true
	

	def booked_bed
		visit_room = VisitRoom.find_by_visit_id(self.id)
		if visit_room.present?
			bed = Bed.find(visit_room.bed_id)
			bed.update(:status=>"true")
		end
	end	


	def self.dashboard(current_user)
		if current_user.has_role?(:doctor)
     	@visits =  Visit.where(:doctor_id=>current_user.id)
    else
    	@visits = Visit.all
   	end 	
	end

	def self.fetch_visit_of_doctors(current_user ,string)
		if current_user.has_role?(:doctor)  
			@visits = self.where("visit_type=? and doctor_id=?", string ,current_user.id)
		else
			@visits = self.where(:visit_type=>string)
		end		
	end

	def update_start_date
		visit_room = VisitRoom.find_by_visit_id(self.id)
		visit_room.update(:start_date=>self.date) if visit_room.present?
	end	

	# def total_amount
	# 	# @total = 0
	# 	# if self.prescription_details.present? 

	# 	# 	self.prescription_details.each do |pd|
	# 	# 		 @total +=pd.quantity.to_i*pd.medicine.charges.to_i
	# 	# 	end
	# 	# end
	# 	# # if self.visit_rooms.present?
	# 	# # 	self.visit_rooms.each do |visit_room|
	# 	# # 		@total += visit_room.room.room_rent.to_i
	# 	# # 	end	
	# 	# # end	
	# 	# # if self.visit_services.present?
	# 	# # 	self.visit_services.each do |visit_service|
	# 	# # 		@total +=visit_service.quantity.to_i*visit_service.service.charges.to_i
	# 	# # 	end	
	# 	# # end
	# 	# return @total	
	# end		
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  include PatientVisits

  def index
    authorize! :read, Visit
    @visits = Visit.dashboard(current_user)
  end

  def show
    authorize! :show, Visit
  end


  def new
    authorize! :new, Visit
    @visit = Visit.new
    @visit.visit_rooms.build
  end

  def edit
    authorize! :edit, Visit
  end

  # POST /visits
  # POST /visits.json
  def create
    authorize! :create, Visit
      @visit =  @patient.visits.build(visit_params) 
        if @visit.save
          if params[:visit][:visit_type] == "opd"
            redirect_to opd_visits_path, notice: 'Opd Visit was successfully created.'
          else
            redirect_to ipd_visits_path, notice: 'Ipd Visit was successfully created.'
          end  
        else
          params[:visit_type] = params[:visit][:visit_type]
          @doctors = User.with_role :doctor
          render :new 
        end 
    end

  def update
    authorize! :update, Visit
      if @visit.update(visit_params)
        redirect_to visits_path, notice: 'Visit was successfully updated.' 
      else
        render :services
      end
  end


  def prescription_detail
    authorize! :read, Visit
    @prescription_details = @visit.prescription_details
  end  

  def opd_visit
    authorize! :read, Visit   
    @visits = Visit.fetch_visit_of_doctors(current_user,"opd")
  end  

  # def services
  #   authorize! :services, Visit    
  #   if @visit.services.present?
  #     @visit.services
  #   else
  #     @visit.services.build
  #   end
  # end  


  # def all_services
  #   authorize! :read, Visit  
  #   @visit = Visit.find(params[:visit_id])
  #   @services = @visit.services
  # end  

  def ipd_visits
    authorize! :read, Visit 
    @visits = Visit.fetch_visit_of_doctors(current_user,"ipd") 
  end  

  def basic_detail
    authorize! :read, Visit 
  end   

  # def genrate_bill
  #   @visit = Visit.find(params[:visit_id])
  #   payment = Payment.where("visit_id=?", params[:visit_id]).last
  #   @services = payment.services
  #end  


  def search_visits
    @from_date= params[:from_date]
    @end_date = params[:end_date]
    if params[:visit_type] == "ipd"
      @visits = Visit.where(:date=>@from_date..@end_date, :doctor_id=>current_user.id,:visit_type=>"ipd")
      #@visits = Visit.where("doctor_id=?" ,current_user.id).joins(:visit_rooms).where("visit_rooms.start_date >= ? and visit_rooms.start_date <= ? ",@from_date, @end_date)
    else
      @visits = Visit.where(:date=>@from_date..@end_date, :doctor_id=>current_user.id,:visit_type=>"opd")
    end  
  end  

  def dashboard
    @discharges = Discharge.all
  end  
  def billing
    @discharges = Discharge.all
  end


  def paid_bill
    @visits = Visit.joins(:payment)
  end  


  private  


    def visit_params
      params.require(:visit).permit(:id, :patient_id, :appointment_id,:room_id,:bed_id, :doctor_id,:visit_type, :date, basic_detail_attributes: [:blood_group, :boold_presure, :patient_id, :visit_id, :weight, :patient_history,:examination_details,:diagnosis, :id], prescription_details_attributes: [:id, :drug_name, :description,:schedule,:visit_id ],services_attributes: [:id, :service_name, :charges ,:visit_id ],visit_rooms_attributes: [:id, :date, :room_id , :bed_id,:visit_id ] )
    end
end

app/helpers/visits_helper.rb
module VisitsHelper

	def get_visit_rooms(visit)
		@visit_room = VisitRoom.find_by_visit_id(visit.id)
		@visit_room.room.room_no if @visit_room.present? && @visit_room.room.present?
	end	

	def get_bed(visit)
		@visit_room = VisitRoom.find_by_visit_id(visit.id)
		@visit_room.bed.bed_no if @visit_room.present? && @visit_room.bed.present?
	end	
end

app/views/visits/_form.html.erb
<%if params[:visit_type] == "ipd" %>
  <%= render 'select_category' %>
<%end%>   
<div class="container">
  <div class="panel-group">
    <div class="panel panel-default">
    <% if params[:visit_type] == "ipd"%>
      <div class="panel-heading">Ipd visit</div>
    <%else%>  
      <div class="panel-heading">Opd visit</div>
    <%end%>    
        <div class="panel-body">
            <%= form_for [@patient, @visit]  do |f| %>

              <% if @visit.errors.any? %>
                <div id="">
                  <ul>
                  <% @visit.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>
              <div class="field">
                <%= f.label :visit_id %><br>
                <% if params[:visit_type] == "ipd"%>
                  <%= f.text_field :id ,class: "form-control",:placeholder=>'Ipd Visit No',disabled: true %>
                <%else%>  

                  <%= f.text_field :id ,class: "form-control",:placeholder=>'Opd Visit No',disabled: true %>
                <%end%>
              </div>

              <div class="field">
                <%= f.label :doctor_id %><br>
                <%= f.select :doctor_id ,@doctors.all.map{|d| [ d.name, d.id ]},{:include_blank=>"Please select doctors"},class: "form-control" %>
              </div>
              <% if params[:visit_type] == "ipd"%>
                <div class="field">
                  <%= f.label :addmision_date %><br>
                  <%= f.text_field :date , class: "form-control start_date_picker " %>
                </div>
                <%= f.fields_for :visit_rooms do |visit_room| %>
                  <% render :partial=>'visit_room', locals: {visit_room: visit_room}%>
                <% end %>
              <%end%>
              <% if params[:visit_type] == "opd"%>
                <div class="field">
                  <%= f.label :visit_date %><br>
                  <%= f.text_field :date , class: "form-control start_date_picker" %>
                </div></br>
              <%end%>

              <div class="field">
                <%= f.hidden_field :visit_type,  :value=>params[:visit_type]  %>
              </div></br>
              <div class="actions">
                <%= f.submit 'save',  :class=>"btn btn-primary",:style=>"margin-top: -59px;" %>
              </div>
            <% end %>
        </div>  
    </div>
  </div>
</div>

app/views/visits/_search_visit_form.html.erb
<div>
  <%=form_tag search_visits_path, :remote=>true do %>
  <div class="col-md-4">
    <%=text_field_tag :from_date,params[:from_date], :class=>"form-control start_date_picker" %>
  </div>
  <div class="col-md-4">  
    <%=text_field_tag :end_date,params[:end_date],:class=>"form-control start_date_picker" %>
  </div>  
    <%if params["action"]=="ipd_visits"%>
      <%=hidden_field_tag :visit_type,'ipd' %>
    <%else%>
      <%=hidden_field_tag :visit_type,'opd' %>
    <%end%>  
    <%=submit_tag 'search', name: nil, class: "btn btn-default"%>
  <%end%>
</div>

app/views/visits/_select_category.html.erb
<div class ="col-md-4 ">
  <%=form_tag search_category_room_path do %>
    <%= select_tag(:category_id, options_for_select(Category.all.map { |c| [c.category_type, c.id] }), {:include_blank=>"select category", :class => 'form-control target'})   %>
  <%end%>
</div>

<div class="panel-body show_room">
</div>  

<div class="panel-body room_beds">
</div>
<script>
  $( ".target" ).change(function() {
    var id = $(".target").val();
    $.get("/categories/"+ id,{}, function(){
    });
  });
</script>

app/views/visits/all_services.html.erb
<div class="container">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading"> services </div>
        <div class="panel-body">
         <p>Registration number:<%=@visit.patient.id%></p>
         <p>Patient name:<%=@visit.patient.patient_name%></p>
         <p>Consultant doctor:<%=@visit.user.name%></p>

          <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Service name</th>
                  <th>Charges</th>
                 </tr>
              </thead>
              <tbody>
                <%=form_tag payment_path(@visit) do %>
  								<%@services.each do |service|%>
  								  <tr>
                      <td>
                      <% if service.paid== "true"%>
                        <%=check_box_tag  "service_ids[]" ,service.id, true , disabled: true, id: "dsadasd" %>
                          <%=service.service_name%>
                      <%else%>
                        <%=check_box_tag  "service_ids[]" ,service.id, false , id: "dsadasd" %>
                          <%=service.service_name%>
                      <%end%>    
                      </td>
               
                      <td>
                        <%=service.charges%>
                      </td> 
                    </tr>
  								<%end%>
                  <div>
                    <%=submit_tag 'payment',:class=>"btn btn-primary"%>
                  </div>
                <%end%>  
              </tbody>
            </table>
            <%#=link_to 'Bill Genrate', visit_genrate_bill_path(@visit),:class=>"btn btn-primary"%>
      </div>  
    </div>
  </div>
</div> 

app/views/visits/basic_detail.html.erb
<div class="container">
  <div class="col-sm-6">
    <div class="panel panel-default">
      <div class="panel-heading"> Opd visit</div>
        <div class="panel-body">
        <%if @visit.visit_type == "ipd"%>
          <p>
            <strong>Ipd no</strong>
            <%= @visit.id %>
          </p>


          <p>
            <strong>Admit Date:</strong>
            <%= @visit.date %>
          </p>
          <p>
            <strong>Room no:</strong>
            <%= get_visit_rooms(@visit) %>
          </p>
          <p>
            <strong>Bed no:</strong>
            <%= get_bed(@visit)%>
          </p>
        <%else%>
          <p>
            <strong>Opd no</strong>
            <%= @visit.id %>
          </p>


          <p>
            <strong>Visit Date:</strong>
            <%= @visit.date %>
          </p>
        <%end%>  

          <p>
            <strong>Patient name</strong>
            <%=@visit.patient.patient_name if @visit.patient.present?%>
          </p>

          <p>
            <strong>Doctor name</strong>
            <%=@visit.user.name if @visit.user.present?%>
          </p>
        </div>  
    </div>
  </div>
</div> 

app/views/visits/billing.html.erb
s<div class="container">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading">Billing </div>
        <div class="panel-body">
          <table  class="table table-striped">
            <thead>
              <tr>
                <th>Id</th>
                <th>Patient Name</th>
                <th>Patient Age</th>
                <th>Visit Type</th>
              </tr>
            </thead>

            <tbody>
              <%  @discharges.each do |discharge| %>
               <%unless discharge.visit.payment.present? %>
              
                    <tr>
                      <td><%= discharge.visit_id%></td>

                    <td><%= discharge.visit.patient.patient_name if discharge.visit.present? && discharge.visit.patient.present? %></td>
                    <td><%= discharge.visit.patient.age if discharge.visit.present? && discharge.visit.patient.present?  %></td>
                    <td><%= discharge.visit.visit_type if discharge.visit.present? %></td>
                    <% if current_user.has_role?(:chasier) %>
                      <td>
                        <%=link_to 'Payment',payment_new_path(discharge.visit)%>
                      </td>
                      <td>
                        <%=link_to 'Add more service',new_visit_visit_service_path(discharge.visit ,:add_item=>'add_item'),:remote=>true,"data-toggle"=>"modal", "data-target"=>"#myModal"%>
                      </td>
                    <%end%>  
                <%end%>  
              <%end%>  

            </tbody>
          </table>
      </div>  
    </div>
  </div>
</div> 




 
<%= render :partial=> 'visit_services/open_popup' %>

app/views/visits/dashboard.html.erb
<div class="container">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading">Visited Patient </div>
        <div class="panel-body">
          <table  class="table table-striped">
            <thead>
              <tr>
                <th>Id</th>
                <th>Patient Name</th>
                <th>Patient Age</th>
                <th>Visit Type</th>
              </tr>
            </thead>

            <tbody>
              <%  @discharges.each do |discharge| %>
                <tr>
                  <td><%= discharge.visit_id%></td>

                <td><%= discharge.visit.patient.patient_name if discharge.visit.present? && discharge.visit.patient.present? %></td>
                <td><%= discharge.visit.patient.age if discharge.visit.present? && discharge.visit.patient.present?  %></td>
                <td><%= discharge.visit.visit_type if discharge.visit.present? %></td> 
              <%end%>  

            </tbody>
          </table>
      </div>  
    </div>
  </div>
</div> 

app/views/visits/edit.html.erb
<h1>Editing Visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/genrate_bill.html.erb
<div class="container">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading"> services </div>
        <div class="panel-body">
         <p>
          <strong>Visit no</strong>
            <%= @visit.id %>
          </p>

          <p>
            <strong>Date:</strong>
            <%= @visit.date %>
          </p>

          <p>
            <strong>Patient name</strong>
            <%=@visit.patient.patient_name%>
          </p>

          <p>
            <strong>Patient age</strong>
            <%=@visit.patient.age%>
          </p>
          <p>
            <strong>Consultant </strong>
            <%=@visit.user.name%>
          </p>

          <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Service name</th>
                  <th>Charges</th>
                 </tr>
              </thead>
              <tbody>
              	<%total =0 %>
								<%@services.each do |service|%>
								<tr>
									<td><%=service.service_name%></td>
									<td><%=service.charges%></td>
									<%total += service.charges.to_i%>
								</tr>	
								<%end%>
								<tr>
									<td>Total</td>
									<td><%=total%></td>
								</tr>	
              </tbody>
            </table>
      </div>  
    </div>
    <button id="print" class="btn btn-primary">Print</button>
  </div>
</div> 


<script>
  $("#print").click(function(){
    window.print();
});
</script>

app/views/visits/index.html.erb
<div class="container">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading">Visits </div>
        <div class="panel-body">
          <table  class="table table-striped">
            <thead>
              <tr>
                <th>Id</th>
                <th>Patient name</th>
                <th>Doctor Name</th>
                <th>Date</th>
                <th>Visit Type</th>
              </tr>
            </thead>

            <tbody>
              <% @visits.each do |visit| %>
                <tr>
                  <td><%=visit.id  %> 
                  <td><%= visit.patient.patient_name %></td>
                  <td><%= visit.user.name if visit.user.present?%>
                  <td><%=visit.date%></td>
                  <td><%=visit.visit_type%></td>
                  <% if can? :service, Visit %>
                    <td><%=link_to'services',  visit_services_path(visit)  %></td>
                  <%end%>  
                  <td><%=link_to 'Payment', visit_all_services_path(visit)%></td>
                  <td><%=link_to 'Paid bill', paid_bill_path(visit)%></td>
                </tr> 
              <% end %>
            </tbody>
          </table>
      </div>  
    </div>
  </div>
</div> 

app/views/visits/opd_visit.html.erb
<div class="container">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading">Opd Visit </div>
        <div class="panel-body">
          <table  class="table table-striped">
          <% if current_user.has_role?(:doctor)%>
            <%=render partial: 'search_visit_form'%>
          <%end%>  
            </br>
            </br>
            <thead>
              <tr>
                <th>OPD No</th>
                <th>Patient name</th>
                <th>Doctor name</th>
                <th>Visit Date</th>
                <th>Register date</th>
              </tr>
            </thead>

            <tbody class="visited_patient">
              <% @visits.each do |visit| %>
                <%unless visit.discharge.present?%>
                  <tr>
                    <td>
                      <% if can? :show, Visit %>
                        <%=link_to visit.id ,visit_path(visit) %>
                      <%else%>
                        <%=visit.id%>
                      <%end%>  
                    </td>
                    <td><%= visit.patient.patient_name %></td>  
                    <td>
                      <%if visit.user.present?%>   
                        <%= visit.user.name %>
                      <%end%>
                    </td>
                    <td><%= visit.date %></td>
                    <td><%=visit.patient.created_at.strftime("%d-%m-%Y")%></td>
                    <td><%#=link_to 'genrate bill',visit_genrate_bill_path(visit)%></td>
                  </tr>
                <%end%>  
              <% end %>
            </tbody>
          </table>
      </div>  
    </div>
  </div>
</div> 

app/views/visits/prescription_detail.html.erb
<div class="container">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading"> Opd visit</div>
        <div class="panel-body">
         <p>
          <strong>Visit no</strong>
            <%= @visit.id %>
          </p>

          <p>
            <strong>Date:</strong>
            <%= @visit.date %>
          </p>

          <p>
            <strong>Patient name</strong>
            <%=@visit.patient.patient_name%>
          </p>

          <p>
            <strong>Patient age</strong>
            <%=@visit.patient.age%>
          </p>
          <p>
            <strong>Consultant </strong>
            <%=@visit.user.name%>
          </p>

          <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Drug Name</th>
                  <th>Description</th>
                  <th>schedule</th>

                  
                </tr>
              </thead>
              <tbody>
                <% @prescription_details.each do |prescription_detail| %>
                  <tr>
                    <td><%=prescription_detail.drug_name%></td>
                    <td><%=prescription_detail.description%></td>
                    <td><%=prescription_detail.schedule%></td>
                  </tr>
                <%end%>
              </tbody>
            </table>
      </div>  
    </div>
    <button id="print" class="btn btn-primary">Print</button>
  </div>
</div> 


<script>
  $("#print").click(function(){
    window.print();
});
</script>

app/views/visits/search_visits.js.erb
<% if params[:visit_type] == "ipd" %>
	$(".admit_patient").html("<%= j render partial: 'search_ipd_visits', locals: {visits: @visits} %>");
<%else%>
	$(".visited_patient").html("<%= j render partial: 'search_ipd_visits', locals: {visits: @visits,visit_type: params[:visit_type]} %>");
<%end%>
 