config/routes.rb
Rails.application.routes.draw do
  resources :rooms  
  resources :beds
  resources :diagnoses
  resources :departments
  resources :department_doctors
  resources :patients do  
  end  
  get 'visit/:id/prescription_detail' => 'visits#prescription_detail', :as=>"prescription_details"
  get '/opd_visit' => 'visits#opd_visit', :as=>"opd_visits"
 
  get '/dashboard'  => 'visits#dashboard', :as=>"dashboard"
  get '/billing'  => 'visits#billing', :as=>"billing"
  get '/paid_bill'  => 'visits#paid_bill', :as=>"paid_bill"
  get '/visit/:visit_id/report_genrate' => 'reports#genrate_report', :as=>"genrate_report" 
  get '/visit/:visit_id/print_receipt' => 'diagnoses#print_receipt', :as=>"print_receipt"  
  
  post '/download_paid_bill'  => 'reports#download_paid_bill', :as=>"downlaod_paid_bill"

  resources :services do 
    
  end   
 

  resources :patient do  
     resources :appointments,only: [:new, :create,:edit,:update] do
    end
  end 

  resources :appointments

  resources :patients do 
     resources :visits do
    end
  end 

  resources :visits do 
    resources :prescription_details,only: [:index, :new, :create,:destroy] do
    end  
  end  

  resources :visits do
    resources :diagnoses do
    end  
  end 

  resources :visits do
    resources :notes do
    end 
  end 

  resources :visits do
    resources :worksheet_details do
    end  
  end 

  resources :discharges
  resources :visits do
    resources :discharges, only: [:new, :create] do
    end  
  end 

  resources :visits do
    resources :visit_rooms, only: [:new, :create,:index,:destroy] do
    end  
  end 

  resources :visits do 
    resources :operation_theaters,  only: [:new,:create,:index,:show] do
    end
  end    

  get '/ipd_visits' => 'visits#ipd_visits', :as=>"ipd_visits"
  get '/visit/:id/basic_detail' => 'visits#basic_detail', :as=>"basic_detail"

 
  devise_for :users
  resources :user
  
  resources :visits do
    get 'all_services' 
    get 'report'
    get 'genrate_bill'
  end  

  get 'visit/:visit_id/payment/new' => 'payments#new', :as=>"payment_new"
  post 'visit/:visit_id/payments' => 'payments#create', :as=>"create_payment"
  post 'visit/:visit_id/payment' => 'payments#payment', :as=>"payment"
  get '/report' => 'reports#index', :as=>"report"

    
  post  '/search_category_room' => 'visits#search_category_room',:as=>"search_category_room"
  post '/search_visit'  => 'visits#search_visits', :as=>"search_visits"

  get '/bed/:bed_id/admit' => 'beds#admit',:as=>"admit"
  get '/country/:country_id/states' => 'patients#states',:as=>"states"
  get '/state/:state_id/cities' => 'patients#cities',:as=>"cities" 

  root 'user#index'

  resources :visits do
    resources :visit_services do 
    end
  end  

  resources :medicines do 
  end  
  get '/export' => 'medicines#export',:as=>"export"
  

resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :rooms
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:edit, :update,:destroy] 

	def index
    authorize! :read, Category
		@categories = Category.all
	end
	
	def  new
    authorize! :create, Category
		@category = Category.new
	end	

	def create
    authorize! :create, Category
    @category = Category.new(category_params)
		if @category.save
  		redirect_to  categories_path 
  	else
  		render :new
  	end
  end

  def edit
    authorize! :edit, Category
  	@category = Category.find(params[:id])
  end	

  def update
    authorize! :update, Category
  	if @category.update(category_params)
  		redirect_to categories_path 
  	else
  		render :edit	
  	end
  end	

  def destroy
    authorize! :destroy, Category
  	if @category.destroy
  		redirect_to categories_path
  	end	
  end

  def show
   @category = Category.find(params[:id])
   @rooms = @category.rooms
  end 


 
	
	private
		def category_params
      params.require(:category).permit(:id,:category_type,:description)
		end	

		def set_category
			@category = Category.find(params[:id])
		end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
  
<p style="display:none;">Category can not be  blank</p>
 <%=form_for @category do |f|%>
  <div> 
    <%=f.label :category%>  
    <%=f.text_field :category_type,:class=>"form-control"%>
  </div>
  <div>
    <%=f.label :description%>   
    <%=f.text_area :description,:class=>"form-control"%>
  </div> 
  <% if params[:action] =="edit"%>
		<%=f.submit 'save'%>
  <%else%>
		<button  type="button" class="btn btn-primary" id="save">Save</button>
	<%end%>	
<%end%>

app/views/categories/_index.html.erb
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add Category</h4>
        </div>
        <div class="modal-body">
         <%=form_for Category.new,:url=>categories_path do |f|%>
          <div> 
            <%=f.label :category%>  
            <%=f.text_field :category_type,:class=>"form-control"%>
          </div>
          <div>
            <%=f.label :description%>   
            <%=f.text_area :description,:class=>"form-control"%>
          </div>  
        </div>
        <div class="modal-footer">
            <%=f.submit 'save',:class=>"btn btn-primary"%>
          <%end%>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>

app/views/categories/_show.html.erb
<table class="table table-bordered">
  <thead>
    <tr>
      <th>Room no</th>
      <th>Room Type</th>
      <th>Room rent</th>
      <th>Total beds</th>
      <th>Booked beds</th>
      <th>Available beds</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <%if room.beds.count > room.beds.where(:status=>"true").count%>
        <tr>
        	<td><%=link_to "#{room.room_no}",room_path(room),:remote=>true %></td>
          <td><%= room.category.category_type if room.category.present? %></td>
          <td><%= room.room_rent %></td>
          <td><%= total_beds = room.beds.count %></td>
          <td><%= booked_beds = room.beds.where(:status=>"true").count%></td>
          <td><%= available_beds = total_beds-booked_beds%>
          </td>
        </tr>
      <%end%>  
    <% end %>
  </tbody>
</table>
 

app/views/categories/edit.js.erb
$(".category_add").html('<%= j render "categories/form"  %>');

app/views/categories/index.html.erb
<div class="container">
  <div class="col-sm-12">
    <div class="panel panel-default">
      <div class="panel-heading">Category </div>
          <div class="panel-body">
            <%if can? :create, Category%>
              <%=link_to 'Add Category', new_category_path, :class=>"btn btn-primary", "data-toggle" => "modal", "data-target" => "#myModal" ,:remote=>:true%>
          	<%end%>
            </br>
          	</br>
            <table class="table table-bordered">
              <thead>
                <tr>
                  <th>Category</th>
                  <th>Description</th>
                  <%if can? :edit, Room%>
                    <th>Edit/Delete</th>
                  <%end%>
                </tr>
              </thead>
              <tbody>
								<%@categories.each do |category| %>
								<tr>
									<td>
										<%=category.category_type%>
									</td>
									<td>	
										<%=category.description%>
									</td>	
                  <%if can? :edit, Category%>
                    <td>
										  <%=link_to 'edit',edit_category_path(category),:remote=>true , "data-toggle" => "modal", "data-target" => "#myModal" %>/<%=link_to 'delete',category_path(category),method: :delete, data: {confirm: "Are you sure?"}%>
                    </td>
                  <%end%>
								<%end%>
              </tbody>
            </table>
          </div>  
    </div>
  </div>
</div>  


  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Add Category</h4>
        </div>
        <div class="modal-body category_add">

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>




<!-- <script>
  $('.category').click(function() {
    var ids = [];
    $(':checked').each(function(i, e) {
        ids.push($(this).val());
    });  
    var checked; 
    if ($(this).is(':checked')) {
      checked = true;
    } else {
      checked = false;
    } 
    $.ajax({
        type: "POST",
        url: "/category/search_room",
        data: { id: ids, checked: checked }
     });     
  });
</script> -->

<!-- <div class="show_room">

</div> -->

app/views/categories/new.js.erb
$(".category_add").html('<%= j render "categories/form"  %>');
$("#save").click(function(){
	if($("#category_category_type").val() == ""){
		$("p").show();
	}
	else{
		$("#new_category").submit();
	}
});

app/views/categories/show.js.erb
// $(".category_rooms").html("<%= j render partial: 'show', locals: {rooms: @rooms} %>");
$(".show_room").html("<%= j render partial: 'show', locals: {rooms: @rooms} %>");